//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLandEditeur.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classe
    {
        public Classe()
        {
            this.Hero = new HashSet<Hero>();
        }
    
        public int Id { get; set; }
        public string NomClasse { get; set; }
        public string Description { get; set; }
        public float StatPoidsStr { get; set; }
        public float StatPoidsDex { get; set; }
        public float StatPoidsInt { get; set; }
        public float StatPoidsStam { get; set; }
        public int MondeId { get; set; }
    
        public virtual Monde Monde { get; set; }
        public virtual ICollection<Hero> Hero { get; set; }
    }
}
