//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLandEditeur.Modele
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RPG_Entities : DbContext
    {
        public RPG_Entities()
            : base("name=RPG_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classe> Classe { get; set; }
        public virtual DbSet<CompteJoueur> CompteJoueur { get; set; }
        public virtual DbSet<EffetItem> EffetItem { get; set; }
        public virtual DbSet<Hero> Hero { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Monde> Monde { get; set; }
        public virtual DbSet<Monstre> Monstre { get; set; }
        public virtual DbSet<ObjetMonde> ObjetMonde { get; set; }
    }
}
