//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLandEditeur.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monde
    {
        public Monde()
        {
            this.Classe = new HashSet<Classe>();
            this.Hero = new HashSet<Hero>();
            this.Item = new HashSet<Item>();
            this.Monstre = new HashSet<Monstre>();
            this.ObjetMonde = new HashSet<ObjetMonde>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string LimiteX { get; set; }
        public string LimiteY { get; set; }
    
        public virtual ICollection<Classe> Classe { get; set; }
        public virtual ICollection<Hero> Hero { get; set; }
        public virtual ICollection<Item> Item { get; set; }
        public virtual ICollection<Monstre> Monstre { get; set; }
        public virtual ICollection<ObjetMonde> ObjetMonde { get; set; }
    }
}
