//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp3Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public Hero()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int CompteJoueurId { get; set; }
        public int Id { get; set; }
        public int Niveau { get; set; }
        public long Experience { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public decimal Argent { get; set; }
        public int StatBaseStr { get; set; }
        public int StatBaseDex { get; set; }
        public int StatBaseInt { get; set; }
        public int StatBaseStam { get; set; }
        public int MondeId { get; set; }
        public int ClasseId { get; set; }
    
        public virtual Classe Classe { get; set; }
        public virtual CompteJoueur CompteJoueur { get; set; }
        public virtual Monde Monde { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
