//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp3Service
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]  
    public partial class Item
    {
        public Item()
        {
            this.EffetItems = new HashSet<EffetItem>();
            this.Heroes = new HashSet<Hero>();
        }

        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Nom { get; set; }
        [DataMember]
        public string Description { get; set; }
        [DataMember]
        public Nullable<int> x { get; set; }
        [DataMember]
        public Nullable<int> y { get; set; }
        [DataMember]
        public int Niveau { get; set; }
        [DataMember]
        public Nullable<decimal> ValeurArgent { get; set; }
        [DataMember]
        public decimal Poids { get; set; }
        [DataMember]
        public int ReqNiveau { get; set; }
        [DataMember]
        public int ReqForce { get; set; }
        [DataMember]
        public int ReqDexterite { get; set; }
        [DataMember]
        public int ReqIntelligence { get; set; }
        [DataMember]
        public int ReqEndurance { get; set; }
        [DataMember]
        public int MondeId { get; set; }
        [DataMember]
        public int Quantite { get; set; }

        [DataMember]
        public virtual ICollection<EffetItem> EffetItems { get; set; }
        [DataMember]
        public virtual Monde Monde { get; set; }
        [DataMember]
        public virtual ICollection<Hero> Heroes { get; set; }
    }
}
