//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp3Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monde
    {
        public Monde()
        {
            this.Classes = new HashSet<Classe>();
            this.Heroes = new HashSet<Hero>();
            this.Items = new HashSet<Item>();
            this.Monstres = new HashSet<Monstre>();
            this.ObjetMondes = new HashSet<ObjetMonde>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string LimiteX { get; set; }
        public string LimiteY { get; set; }
    
        public virtual ICollection<Classe> Classes { get; set; }
        public virtual ICollection<Hero> Heroes { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Monstre> Monstres { get; set; }
        public virtual ICollection<ObjetMonde> ObjetMondes { get; set; }
    }
}
