//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp3Service
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    

    [DataContract(IsReference = true)]
    public partial class Monde
    {
        public Monde()
        {
            this.Classes = new HashSet<Classe>();
            this.Heroes = new HashSet<Hero>();
            this.Items = new HashSet<Item>();
            this.Monstres = new HashSet<Monstre>();
            this.ObjetMondes = new HashSet<ObjetMonde>();
        }

        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Description { get; set; }
        [DataMember]
        public string LimiteX { get; set; }
        [DataMember]
        public string LimiteY { get; set; }

        [DataMember]
        public virtual ICollection<Classe> Classes { get; set; }
        [DataMember]
        public virtual ICollection<Hero> Heroes { get; set; }
        [DataMember]
        public virtual ICollection<Item> Items { get; set; }
        [DataMember]
        public virtual ICollection<Monstre> Monstres { get; set; }
        [DataMember]
        public virtual ICollection<ObjetMonde> ObjetMondes { get; set; }
    }
}
