//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLand
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryItem
    {
        public int ItemID { get; set; }
        public int RecoverAmount { get; set; }
        public short RecoveryType { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
