//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLand
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spell
    {
        public Spell()
        {
            this.Heroes = new HashSet<Hero>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public int ReqLevel { get; set; }
        public float MagicPotency { get; set; }
        public short SpellType { get; set; }
    
        public virtual ICollection<Hero> Heroes { get; set; }
    }
}
