//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classe
    {
        public Classe()
        {
            this.Heroes = new HashSet<Hero>();
        }
    
        public int Id { get; set; }
        public string NomClasse { get; set; }
        public string Description { get; set; }
        public float StatPoidsStr { get; set; }
        public float StatPoidsDex { get; set; }
        public float StatPoidsInt { get; set; }
        public float StatPoidsStam { get; set; }
        public int MondeId { get; set; }
    
        public virtual Monde Monde { get; set; }
        public virtual ICollection<Hero> Heroes { get; set; }
    }
}
