//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public Hero()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int CompteJoueurId { get; set; }
        public int Id { get; set; }
        public int Niveau { get; set; }
        public long Experience { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public decimal Argent { get; set; }
        public int StatBaseStr { get; set; }
        public int StatBaseDex { get; set; }
        public int StatBaseInt { get; set; }
        public int StatBaseStam { get; set; }
        public int MondeId { get; set; }
        public int ClasseId { get; set; }
    
        public virtual Classe Classe { get; set; }
        public virtual CompteJoueur CompteJoueur { get; set; }
        public virtual Monde Monde { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
