//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLand.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RpgGameEntities : DbContext
    {
        public RpgGameEntities()
            : base("name=RpgGameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Classe> Classes { get; set; }
        public DbSet<CompteJoueur> CompteJoueurs { get; set; }
        public DbSet<EffetItem> EffetItems { get; set; }
        public DbSet<Hero> Heroes { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<Monde> Mondes { get; set; }
        public DbSet<Monstre> Monstres { get; set; }
        public DbSet<ObjetMonde> ObjetMondes { get; set; }
    }
}
