//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public Map()
        {
            this.Map1 = new HashSet<Map>();
            this.Maps = new HashSet<Map>();
            this.Monsters = new HashSet<Monster>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Level { get; set; }
        public int ReqLevel { get; set; }
    
        public virtual ICollection<Map> Map1 { get; set; }
        public virtual ICollection<Map> Maps { get; set; }
        public virtual ICollection<Monster> Monsters { get; set; }
    }
}
