//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        public Monster()
        {
            this.Maps = new HashSet<Map>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Level { get; set; }
        public int StatHP { get; set; }
        public float StatDMGmin { get; set; }
        public float StatDMGmax { get; set; }
    
        public virtual ICollection<Map> Maps { get; set; }
    }
}
