//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLand.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rpggameEntities : DbContext
    {
        public rpggameEntities()
            : base("name=rpggameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Hero> Heroes { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<Map> Maps { get; set; }
        public DbSet<Monster> Monsters { get; set; }
        public DbSet<PlayerHero> PlayerHeroes { get; set; }
        public DbSet<PlayerInventory> PlayerInventories { get; set; }
        public DbSet<RecoveryItem> RecoveryItems { get; set; }
        public DbSet<Spell> Spells { get; set; }
        public DbSet<UserAccount> UserAccounts { get; set; }
    }
}
